-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.asignatura
(
    docente_id integer NOT NULL,
    hora_fin time(6) without time zone NOT NULL,
    hora_inicio time(6) without time zone NOT NULL,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    salon integer NOT NULL,
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT asignatura_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.docente
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    usuario_id integer NOT NULL,
    especialidad character varying(50) COLLATE pg_catalog."default",
    nombre_docente character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT docente_pkey PRIMARY KEY (id),
    CONSTRAINT docente_usuario_id_key UNIQUE (usuario_id)
    );

CREATE TABLE IF NOT EXISTS public.estudiante
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    usuario_id integer NOT NULL,
    grado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre_estudiante character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estudiante_pkey PRIMARY KEY (id),
    CONSTRAINT estudiante_usuario_id_key UNIQUE (usuario_id)
    );

CREATE TABLE IF NOT EXISTS public.rol
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT rol_pkey PRIMARY KEY (id),
    CONSTRAINT rol_nombre_key UNIQUE (nombre)
    );

CREATE TABLE IF NOT EXISTS public.usuario
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    rol_id integer,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT usuario_email_key UNIQUE (email),
    CONSTRAINT usuario_username_key UNIQUE (username)
    );

ALTER TABLE IF EXISTS public.asignatura
    ADD CONSTRAINT fkohalv3xtfw1nl4uf6qvbw2gul FOREIGN KEY (docente_id)
    REFERENCES public.docente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.docente
    ADD CONSTRAINT fkrvjjrj83o0fs546tv8v57rg6b FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS docente_usuario_id_key
    ON public.docente(usuario_id);


ALTER TABLE IF EXISTS public.estudiante
    ADD CONSTRAINT fks6tki8rbjso4kwof8pdlfufow FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS estudiante_usuario_id_key
    ON public.estudiante(usuario_id);


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT fkshkwj12wg6vkm6iuwhvcfpct8 FOREIGN KEY (rol_id)
    REFERENCES public.rol (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;

END;